name: Build

on:
  push:
    branches: [ "main", "workflow" ]
  pull_request:
    branches: [ "main", "workflow" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [x64]
        os_flavor: [win-x64, linux-x64, osx-x64]
        project: [RXDKNeighborhood]
        project_lowercase: [rxdkneighborhood]
        include:
          - os_flavor: win-x64
            archive_ext: zip
          - os_flavor: linux-x64
            archive_ext: tar
          - os_flavor: osx-x64
            archive_ext: tar

    steps:
    - uses: actions/checkout@v5.0.0
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.3.1
      with:
        dotnet-version: 8.0.x
    - name: Publish
      run: dotnet publish ./${{ matrix.project }}/${{ matrix.project }}.csproj -p:Platform=${{ matrix.arch }} -r ${{ matrix.os_flavor }} -c Release -p:SelfContained=true -p:PublishSingleFile=true -p:PublishReadyToRun=true -p:TrimUnusedDependencies=false -p:DebugType=None -p:DebugSymbols=false -p:AvaloniaUseCompiledBindingsByDefault=true --output ${{ github.workspace }}/artifacts/${{ matrix.project }}/${{ matrix.os_flavor }}-${{ matrix.arch }}
    - name: Check publish output
      run: ls -laR ${{ github.workspace }}/artifacts/${{ matrix.project }}/
    - name: Chmod (Unix)
      if: ${{ matrix.os_flavor == 'linux-x64' || matrix.os_flavor == 'osx-x64' }}
      run: chmod +x ${{ github.workspace }}/artifacts/${{ matrix.project }}/${{ matrix.os_flavor }}-${{ matrix.arch }}/${{ matrix.project_lowercase }}
    - name: Compress binaries
      run: 7z a ${{ github.workspace }}/${{ matrix.project }}-${{ matrix.os_flavor }}.${{ matrix.archive_ext }} ${{ github.workspace }}/artifacts/${{ matrix.project }}/${{ matrix.os_flavor }}-${{ matrix.arch }}/*
    - name: Create Draft Release
      uses: softprops/action-gh-release@v2.3.2
      if: startsWith(github.ref, 'refs/heads/main')
      with:
        tag_name: latest
        draft: true
        files: |
          ${{ github.workspace }}/${{ matrix.project }}-${{ matrix.os_flavor }}.${{ matrix.archive_ext }}
    - name: Create Release
      uses: softprops/action-gh-release@v2.3.2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ${{ github.workspace }}/${{ matrix.project }}-${{ matrix.os_flavor }}.${{ matrix.archive_ext }}
